
/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'arkr' at '11/2/19 8:20 PM' with Gradle 2.6
 *
 * @author arkr, @date 11/2/19 8:20 PM
 */
public class LibraryTest {
}
